package sugarcube.rh_rag_assistant.chat;

import org.jspecify.annotations.NonNull;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;
import org.springframework.ai.chat.client.ChatClientMessageAggregator;
import org.springframework.ai.chat.client.ChatClientRequest;
import org.springframework.ai.chat.client.ChatClientResponse;
import org.springframework.ai.chat.client.advisor.api.AdvisorChain;
import org.springframework.ai.chat.client.advisor.api.BaseAdvisor;
import org.springframework.ai.chat.client.advisor.api.CallAdvisorChain;
import org.springframework.ai.chat.client.advisor.api.StreamAdvisorChain;
import org.springframework.ai.chat.memory.ChatMemory;
import org.springframework.ai.chat.messages.Message;
import org.springframework.ai.chat.model.ChatResponse;
import reactor.core.publisher.Flux;

public class PromptLoggingAdvisor implements BaseAdvisor {

    private static final Logger logger = LoggerFactory.getLogger(PromptLoggingAdvisor.class);

    private static final String BORDER = "=".repeat(80);

    private final int order;

    public PromptLoggingAdvisor(int order) {
        this.order = order;
    }

    @Override
    public @NonNull ChatClientResponse adviseCall(@NonNull ChatClientRequest request, CallAdvisorChain chain) {
        logPrompt(request);
        ChatClientResponse response = chain.nextCall(request);
        logResponse(request, response);
        return response;
    }

    @Override
    public @NonNull Flux<ChatClientResponse> adviseStream(@NonNull ChatClientRequest request, StreamAdvisorChain chain) {
        logPrompt(request);
        Flux<ChatClientResponse> responses = chain.nextStream(request);
        // aggregates stream tokens and logs full answer once
        return  new ChatClientMessageAggregator()
                .aggregateChatClientResponse(responses,
                        agg -> logResponse(request, agg));
    }

    private void logResponse(ChatClientRequest request, ChatClientResponse response) {
        if (!logger.isDebugEnabled()) {
            return;
        }

        Object conversationId = request.context().get(ChatMemory.CONVERSATION_ID);
        String answer = extractText(response);
        logger.debug(">{}\n -- Answer generated by model [conversationId={}]\n {}{}\n{}",
                BORDER, conversationId, BORDER, answer, BORDER);
    }

    private void logPrompt(ChatClientRequest request) {
        if (!logger.isInfoEnabled()) {
            return;
        }
        Object conversationId = request.context().get(ChatMemory.CONVERSATION_ID);
        StringBuilder prompt = new StringBuilder();
        for (Message message : request.prompt().getInstructions()){
            prompt.append("\n┌── ").append(message.getMessageType()).append(" ──\n");
            prompt.append(message.getText());
        }
        logger.debug(">{}\n -- Prompt sent to model [conversationId={}]\n {}{}\n{}",
                BORDER, conversationId, BORDER, prompt, BORDER);
    }

    private String extractText(ChatClientResponse response) {
        ChatResponse chatResponse = response.chatResponse();
        if (chatResponse == null || chatResponse.getResult() == null) {
            return "(no content)";
        }
        return chatResponse.getResult().getOutput().getText();
    }

    @Override
    public @NonNull ChatClientRequest before(@NonNull ChatClientRequest request, @NonNull AdvisorChain chain) {
        return request;
    }

    @Override
    public @NonNull ChatClientResponse after(@NonNull ChatClientResponse response, @NonNull AdvisorChain chain) {
        return response;
    }

    @Override
    public int getOrder() {
        return order;
    }
}
